# fly.toml app configuration file generated for wasp-project-server on 2023-08-15T09:35:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wasp-project-server"
primary_region = "mia"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
